/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');
	var Item = require('models/Item');
	
	var ModalItemTemplate = require('text!views/modalComponents/tpl/ModalItemTemplate.html');


	var ItemModal = JSetup.View.extend({
		template : _.template(ModalItemTemplate),

		/** The declared form Regions. */
		regions : {
			dataTableItemRegion : '.datatable-item',
		},
		
		/** The form events you'd like to listen */
		events : {
			'click .btnSearchItem' : 'searchItem',
			'click .btnClearItem' : 'clearModal',
			'click tr' : 'selectRow',
			'keypress' : 'treatKeypress',
		},

		/** All the important fields must be here. */		
		ui : {
			loadButton : '.button-loading',
    		inputModalName : '.inputModalName',
    		inputModalItemType : '.inputModalItemType',
    		inputModalIdentifier : '.inputModalIdentifier',
    		inputModalDescription : '.inputModalDescription',
		
			form : '#formSearchItem',
			modalScreen : '.modal',
		},
		treatKeypress : function (e){
		    if (util.enterPressed(e)) {
	    		e.preventDefault();
	    		this.searchItem();
	    	}
		},

		/** First function called, like a constructor. */
		initialize : function(opt) {
			var that = this;

			this.onSelectModel = opt.onSelectModel;
			this.suggestConfig = opt.suggestConfig;

			this.itemCollection = new Item.PageCollection();
			this.itemCollection.state.pageSize = 5;
			this.itemCollection.on('fetching', this.startFetch, this);
			this.itemCollection.on('fetched', this.stopFetch, this);
			
			this.dataTableItem = new JSetup.DataTable({
				row : JSetup.RowClick,
				columns : this.getColumns(),
				collection : this.itemCollection,
			});
			this.setValue(opt.initialValue);
		},
		
		/** Called after DOM´s ready.*/
		onShowView :  function() {
			var that = this;
		  	
		  	
		  	
		  	
	
			that.dataTableItemRegion.show(this.dataTableItem);
					
			if (that.suggestConfig) {
				that.suggestConfig.collection = that.itemCollection;
				that.suggestConfig.onSelect = function(json) {
					var model = new JSetup.BaseModel(json)
					that.onSelectModel(model);
					if (json) {
						that.modelSelect = model
					} else
						that.modelSelect = null;
				}
				util.configureSuggest(that.suggestConfig);
				that.suggestConfig.field.change(function(e) {
					if(!that.suggestConfig.field.val()){
						that.clear();
					}
				})
			}		
		},

		searchItem : function() {
			var that = this;
			this.itemCollection.filterQueryParams = {
	    		name : this.ui.inputModalName.escape(), 
	    		itemType : this.ui.inputModalItemType.escape(), 
	    		identifier : this.ui.inputModalIdentifier.escape(), 
	    		description : this.ui.inputModalDescription.escape(), 
			};

			this.itemCollection.getFirstPage({
				resetState : true,
				success : function(_coll, _resp, _opt) {
					//caso queira algum tratamento de sucesso adicional
				},
				error : function(_coll, _resp, _opt) {
					console.error(_coll, _resp, _opt)
				}
			});
		},

		selectRow : function(e) {
			var modelItem = util.getWrappedModel(e);
			if (modelItem){
				this.modelSelect = modelItem; 
				this.onSelectModel(modelItem);
			}
		},
		
		getJsonValue : function() {
			if (_.isEmpty(this.modelSelect) && _.isEmpty(this.jsonValue)) {
				return null;
			}
			if (this.modelSelect) {
				return this.modelSelect.toJSON();
			} else {
				return this.jsonValue;
			}
		},
		
		getRawValue : function() {
			var json = this.getJsonValue();
			if(json )
				return json.id
			return null;
		},
		
		getValue : function() {
			return this.modelSelect;
		},

		setValue : function(value) {
			this.jsonValue = value;
		},

		getColumns : function() {
			var columns = [	

		{
				name : "name",
				sortable : true,
				editable : false,
				label 	 : "Nome",
				cell : JSetup.CustomStringCell
			}, 
					{
				name : "itemType",
				sortable : true,
				editable : false,
				label 	 : "Tipo",
				cell : JSetup.CustomStringCell
			}, 
					{
				name : "identifier",
				sortable : true,
				editable : false,
				label 	 : "Identificador",
				cell : JSetup.CustomStringCell
			}, 
					{
				name : "description",
				sortable : true,
				editable : false,
				label 	 : "Descrição",
				cell : JSetup.CustomStringCell
			}, 
						];
			return columns;
		},

		hidePage : function() {
			this.ui.modalScreen.modal('hide');
		},

		showPage : function() {
			this.clearModal();
			this.ui.modalScreen.modal('show');
			
			this.searchItem();
		},

		clear : function() {
			this.clearModal();
		},
		clearModal : function() {
			this.modelSelect = null;
			this.jsonValue = null;
			this.itemCollection.reset();
			util.scrollUpModal();
			this.ui.form.get(0).reset();
		},
		
		// Executada depois da consulta concluida.
		stopFetch : function() {
			this.ui.loadButton.button('reset');
			util.stopSpinner();
			util.scrollDownModal();
		},
		
		// Executada Antes da realização da consulta.
		startFetch : function() {
			this.ui.loadButton.button('loading');
			util.showSpinner('spinItem');
		},
	});

	return ItemModal;
});
