/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');
	var Permission = require('models/Permission');
	
	var ModalPermissionTemplate = require('text!views/modalComponents/tpl/ModalPermissionTemplate.html');


	var PermissionModal = JSetup.View.extend({
		template : _.template(ModalPermissionTemplate),

		/** The declared form Regions. */
		regions : {
			dataTablePermissionRegion : '.datatable-permission',
		},
		
		/** The form events you'd like to listen */
		events : {
			'click .btnSearchPermission' : 'searchPermission',
			'click .btnClearPermission' : 'clearModal',
			'click tr' : 'selectRow',
			'keypress' : 'treatKeypress',
		},

		/** All the important fields must be here. */		
		ui : {
			loadButton : '.button-loading',
    		inputModalName : '.inputModalName',
    		inputModalDescription : '.inputModalDescription',
    		inputModalOperation : '.inputModalOperation',
    		inputModalTagReminder : '.inputModalTagReminder',
		
			form : '#formSearchPermission',
			modalScreen : '.modal',
		},
		treatKeypress : function (e){
		    if (util.enterPressed(e)) {
	    		e.preventDefault();
	    		this.searchPermission();
	    	}
		},

		/** First function called, like a constructor. */
		initialize : function(opt) {
			var that = this;

			this.onSelectModel = opt.onSelectModel;
			this.suggestConfig = opt.suggestConfig;

			this.permissionCollection = new Permission.PageCollection();
			this.permissionCollection.state.pageSize = 5;
			this.permissionCollection.on('fetching', this.startFetch, this);
			this.permissionCollection.on('fetched', this.stopFetch, this);
			
			this.dataTablePermission = new JSetup.DataTable({
				row : JSetup.RowClick,
				columns : this.getColumns(),
				collection : this.permissionCollection,
			});
			this.setValue(opt.initialValue);
		},
		
		/** Called after DOM´s ready.*/
		onShowView :  function() {
			var that = this;
		  	
		  	
		  	
	
			that.dataTablePermissionRegion.show(this.dataTablePermission);
					
			if (that.suggestConfig) {
				that.suggestConfig.collection = that.permissionCollection;
				that.suggestConfig.onSelect = function(json) {
					var model = new JSetup.BaseModel(json)
					that.onSelectModel(model);
					if (json) {
						that.modelSelect = model
					} else
						that.modelSelect = null;
				}
				util.configureSuggest(that.suggestConfig);
				that.suggestConfig.field.change(function(e) {
					if(!that.suggestConfig.field.val()){
						that.clear();
					}
				})
			}		
		},

		searchPermission : function() {
			var that = this;
			this.permissionCollection.filterQueryParams = {
	    		name : this.ui.inputModalName.escape(), 
	    		description : this.ui.inputModalDescription.escape(), 
	    		operation : this.ui.inputModalOperation.escape(), 
			};

			this.permissionCollection.getFirstPage({
				resetState : true,
				success : function(_coll, _resp, _opt) {
					//caso queira algum tratamento de sucesso adicional
				},
				error : function(_coll, _resp, _opt) {
					console.error(_coll, _resp, _opt)
				}
			});
		},

		selectRow : function(e) {
			var modelPermission = util.getWrappedModel(e);
			if (modelPermission){
				this.modelSelect = modelPermission; 
				this.onSelectModel(modelPermission);
			}
		},
		
		getJsonValue : function() {
			if (_.isEmpty(this.modelSelect) && _.isEmpty(this.jsonValue)) {
				return null;
			}
			if (this.modelSelect) {
				return this.modelSelect.toJSON();
			} else {
				return this.jsonValue;
			}
		},
		
		getRawValue : function() {
			var json = this.getJsonValue();
			if(json )
				return json.id
			return null;
		},
		
		getValue : function() {
			return this.modelSelect;
		},

		setValue : function(value) {
			this.jsonValue = value;
		},

		getColumns : function() {
			var columns = [	

		{
				name : "name",
				sortable : true,
				editable : false,
				label 	 : "Nome",
				cell : JSetup.CustomStringCell
			}, 
					{
				name : "description",
				sortable : true,
				editable : false,
				label 	 : "Descrição",
				cell : JSetup.CustomStringCell
			}, 
					{
				name : "operation",
				sortable : true,
				editable : false,
				label 	 : "Operação",
				cell : JSetup.CustomStringCell
			}, 
									];
			return columns;
		},

		hidePage : function() {
			this.ui.modalScreen.modal('hide');
		},

		showPage : function() {
			this.clearModal();
			this.ui.modalScreen.modal('show');
			
			this.searchPermission();
		},

		clear : function() {
			this.clearModal();
		},
		clearModal : function() {
			this.modelSelect = null;
			this.jsonValue = null;
			this.permissionCollection.reset();
			util.scrollUpModal();
			this.ui.form.get(0).reset();
		},
		
		// Executada depois da consulta concluida.
		stopFetch : function() {
			this.ui.loadButton.button('reset');
			util.stopSpinner();
			util.scrollDownModal();
		},
		
		// Executada Antes da realização da consulta.
		startFetch : function() {
			this.ui.loadButton.button('loading');
			util.showSpinner('spinPermission');
		},
	});

	return PermissionModal;
});
