/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
package com.robsonmrsp.netflics.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;

import org.hibernate.envers.Audited;
import java.time.LocalDate;
import java.time.LocalDateTime;
	
import java.util.ArrayList;
import java.util.List;

import com.robsonmrsp.netflics.core.model.AbstractMultitenantEntity;

@Entity
@Audited
@Table(name = "LANGUAGE")
public class Language extends AbstractMultitenantEntity{
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)	
	private Integer id;
	
	@Column(name = "NAME" )
	private String name;		
	
	@OneToMany(mappedBy="language")
	private List<Movie> movies;	
		
		
	public  Language() {
		
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public void setMovies(List<Movie> movies){
		this.movies = movies;
	}
	
	public List<Movie>  getMovies() {
		if(this.movies == null){
			setMovies(new ArrayList<Movie>());
		}
		return this.movies;
	}
		
	public boolean addMovies(Movie movie){
		movie.setLanguage(this);
		return getMovies().add(movie);
	}
	
	public boolean removeMovies(Movie movie){
		movie.setLanguage(null);
		return getMovies().remove(movie);
	}
	
	
}
//generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20