/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;

import org.hibernate.envers.Audited;
import java.time.LocalDate;
import java.time.LocalDateTime;
	
import java.util.ArrayList;
import java.util.List;

import com.robsonmrsp.netflics.core.model.AbstractMultitenantEntity;

@Entity
@Audited
@Table(name = "MOVIE")
public class Movie extends AbstractMultitenantEntity{
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)	
	private Integer id;
	
	@Column(name = "SINOPSIS" )
	private String sinopsis;		
	
	@Column(name = "RELEASE_DATE")
	private LocalDate releaseDate;  
				
	@Column(name = "BUDGET")
	private Double budget;  	
			
	@Column(name = "TITLE" )
	private String title;		
	
	@OneToMany()
	private List<Genre> genres;	
		
	@OneToMany()
	private List<Actor> cast;	
		
	@ManyToOne
	@JoinColumn(name = "ID_LANGUAGE")
	private Language language;
			
		
	public  Movie() {
		
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getSinopsis() {
		return sinopsis;
	}

	public void setSinopsis(String sinopsis) {
		this.sinopsis = sinopsis;
	}
	public LocalDate getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(LocalDate releaseDate) {
		this.releaseDate = releaseDate;
	}
	public Double getBudget() {
		return budget;
	}

	public void setBudget(Double budget) {
		this.budget = budget;
	}
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	public void setGenres(List<Genre> genres){
		this.genres = genres;
	}
	
	public List<Genre>  getGenres() {
		if(this.genres == null){
			setGenres(new ArrayList<Genre>());
		}
		return this.genres;
	}
		
	public boolean addGenres(Genre genre){
		return getGenres().add(genre);
	}
	
	public boolean removeGenres(Genre genre){
		return getGenres().remove(genre);
	}
	
	public void setCast(List<Actor> cast){
		this.cast = cast;
	}
	
	public List<Actor>  getCast() {
		if(this.cast == null){
			setCast(new ArrayList<Actor>());
		}
		return this.cast;
	}
		
	public boolean addCast(Actor actor){
		return getCast().add(actor);
	}
	
	public boolean removeCast(Actor actor){
		return getCast().remove(actor);
	}
	
	public Language getLanguage() {
		return language;
	}
	
	public void setLanguage(Language language) {
		this.language = language;
	}
	
	
}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56