/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.UniqueConstraint;		

import org.hibernate.envers.Audited;
import java.time.LocalDate;
import java.time.LocalDateTime;
	
import java.util.ArrayList;
import java.util.List;

import com.robsonmrsp.netflics.core.model.AbstractEntity;

@Entity
@Audited
@Table(name = "PERMISSION", uniqueConstraints = {
		@UniqueConstraint(name = "PERMISSION_NAME", columnNames = { "NAME" }), 
})
public class Permission extends AbstractEntity{
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)	
	private Integer id;
	
	@Column(name = "NAME" )
	private String name;		
	
	@Column(name = "DESCRIPTION" )
	private String description;		
	
	@Column(name = "OPERATION" )
	private String operation;		
	
	@Column(name = "TAG_REMINDER" )
	private String tagReminder;		
	
    @ManyToMany
    @JoinTable(name="PERMISSION_ROLE", joinColumns = @JoinColumn(name = "ID_PERMISSION", referencedColumnName = "ID"), inverseJoinColumns = @JoinColumn(name = "ID_ROLE", referencedColumnName = "ID") )
    private List<Role> roles;
    
    @ManyToMany
    @JoinTable(name="PERMISSION_GROUP", joinColumns = @JoinColumn(name = "ID_PERMISSION", referencedColumnName = "ID"), inverseJoinColumns = @JoinColumn(name = "ID_GROUP", referencedColumnName = "ID") )
    private List<Group> groups;
    
	@ManyToOne
	@JoinColumn(name = "ID_ITEM")
	private Item item;
			
		
	public  Permission() {
		
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}
	public String getTagReminder() {
		return tagReminder;
	}

	public void setTagReminder(String tagReminder) {
		this.tagReminder = tagReminder;
	}
	public void setRoles(List<Role> roles){
		this.roles = roles;
	}
	
	public List<Role>  getRoles() {
		if(this.roles == null){
			setRoles(new ArrayList<Role>());
		}
		return this.roles; 
	}
		
	public boolean addRoles(Role role){	
		return getRoles().add(role);
	}
	
	public boolean removeRoles(Role role){	
		return getRoles().remove(role);
	}
	public void setGroups(List<Group> groups){
		this.groups = groups;
	}
	
	public List<Group>  getGroups() {
		if(this.groups == null){
			setGroups(new ArrayList<Group>());
		}
		return this.groups; 
	}
		
	public boolean addGroups(Group group){	
		return getGroups().add(group);
	}
	
	public boolean removeGroups(Group group){	
		return getGroups().remove(group);
	}
	public Item getItem() {
		return item;
	}
	
	public void setItem(Item item) {
		this.item = item;
	}
	
	
}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56