/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');	
	var PageMovieTemplate = require('text!views/movie/tpl/PageMovieTemplate.html');

	var Movie = require('models/Movie');

	var PageMovie = JSetup.View.extend({
		template : _.template(PageMovieTemplate),

		/** The declared form Regions. */
		regions : {
			dataTableMovieRegion : '.datatable-movie',
		},
		
		/** The form events you'd like to listen */
		events : {
			'click 	.reset-button' : 'resetMovie',			
			'keypress' : 'treatKeypress',
			
			'click 	.search-button' : 'searchMovie',
			'click  .show-advanced-search-button' : 'toggleAdvancedForm',
		},
		
		/** All the important fields must be here. */		
		ui : {
			loadButton : '.loading-button',
			inputSinopsis : '#inputSinopsis',
			inputReleaseDate : '#inputReleaseDate',
			inputBudget : '#inputBudget',
			inputTitle : '#inputTitle',
			form : '#formMovieFilter',
			advancedSearchForm : '.advanced-search-form',
		},
		
		/** First function called, like a constructor. */		
		initialize : function() {
			var that = this;
			this.movies = new Movie.PageCollection();
			
			this.dataTableMovie = new JSetup.DataTable({
				columns : this.getColumns(),
				collection : this.movies,
				onFetching : this.startFetch,
				onFetched : this.stopFetch,
				view : this
			});			
		},

		/** Called after DOM´s ready.*/		
		onShowView : function() {
			var that = this;
			this.ui.inputReleaseDate.date();
			this.ui.inputBudget.decimal();
		
			this.dataTableMovieRegion.show(this.dataTableMovie);
		
			this.dataTableMovie.recoveryLastQuery();
		},
		
		 searchMovie : function(){		                                                                   
		 	var that = this;                                                                                                   
		 	this.dataTableMovie.getFirstPage({                                                                             
		 		success : function(_coll, _resp, _opt) {                                                                       
		 			//console.info('Consulta para o grid movie');                                         
		 		},                                                                                                             
		 		error : function(_coll, _resp, _opt) {                                                                         
		 			//console.error(_resp.responseText || (_resp.getResponseHeader && _resp.getResponseHeader('exception')));  
		 		},                                                                                                             
		 		filterQueryParams : {                                                                                          
		     		sinopsis : this.ui.inputSinopsis.escape(),                                   
		     		releaseDate : this.ui.inputReleaseDate.escape(),                                   
		 	    	budget : this.ui.inputBudget.escape(true),                               
		     		title : this.ui.inputTitle.escape(),                                   
		 		}                                                                                                              
		 	})                                                                                                                 
		 },																													   
		
		resetMovie : function(){
			this.ui.form.get(0).reset();
			this.movies.reset();
		},
				
		getColumns : function() {
			var that = this;
			var columns = [
			{
				name : "sinopsis",
				sortable : true,
				editable : false,
				label 	 : "Sinopsis",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "releaseDate",
				sortable : true,
				editable : false,
				label 	 : "Release date",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "budget",
				sortable : true,
				editable : false,
				label 	 : "Budget",
		  		cell : JSetup.DecimalCell,	
			}, 
			{
				name : "title",
				sortable : true,
				editable : false,
				label 	 : "Title",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "acoes",
				label : "Ações(Editar, Deletar)",
				editable : false,
				sortable : false,
				cell : JSetup.ActionCell.extend({
					buttons : that.getCellButtons(),
					context : that,
				})
			} ];
			return columns;
		},
		
		getCellButtons : function() {
			var that = this;
			var buttons = [];

			buttons.push({
				id : 'edit_button',
				type : 'primary',
				icon : 'fa-pencil',
				customClass : 'auth[edit-movie,disable]',
				hint : 'Editar Movie',
				onClick : that.editModel,
			}, {
				id : 'delete_button',
				type : 'danger',
				customClass : 'auth[delete-movie, disable]',
				icon : 'fa-trash',
				hint : 'Remover Movie',
				onClick : that.deleteModel,
			});

			return buttons;
		},

		deleteModel : function(model) {
			var that = this;
			
			var modelTipo = new Movie.Model({id : model.id});
			
			util.confirm({
				title : "Importante",
				text : "Tem certeza que deseja remover o registro [ " + model.get('id') + " ] ?",
				onConfirm : function() {
					modelTipo.destroy({
						success : function() {
							that.movies.remove(model);
							util.alert({title : "Concluido", text : "Registro removido com sucesso!"});
						},
					});
				}
			});
		},

		editModel : function(model) {
			util.goPage("app/editMovie/" + model.get('id'));
		},

		
		// additional functions
		toggleAdvancedForm : function() {
			this.ui.advancedSearchForm.slideToggle("slow");
		},

		treatKeypress : function(e) {
			if (util.enterPressed(e)) {
				e.preventDefault();
				this.searchMovie();
			}
		},
		startFetch : function() {
			util.loadButton(this.ui.loadButton)
		},

		stopFetch : function() {
			util.resetButton(this.ui.loadButton)
		}
	});

	return PageMovie;
});
