/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');

	var TemplateFormPermissions = require('text!views/permission/tpl/FormPermissionTemplate.html');
	var ModalItem = require('views/modalComponents/ModalItem');
	
	var Permission = require('models/Permission');
	
	var FormPermissions = JSetup.View.extend({
		template : _.template(TemplateFormPermissions),

		/** The declared form Regions. */
		regions : {
			modalItemRegion : '.modal-item-container',
		},

		/** The form events you'd like to listen */
		events : {
			'click 	.save' : 'save',
			'click 	.save-continue' : 'saveAndContinue',
			'click .search-item-modal' : 'showModalItem',
			'change  #inputName' : 'changeName',	
		},
		/** All the important fields must be here. */
		ui : {
			inputId : '#inputId',
			saveButton : '.button-saving',
			inputName : '#inputName',
			inputDescription : '#inputDescription',
			inputOperation : '#inputOperation',
			inputTagReminder : '#inputTagReminder',
			inputItemId : '#inputItemId',
			inputItemName : '#inputItemName',
			form : '#formPermission',
		},
		
		/** First function called, like a constructor. */
		initialize : function(options) {
			var that = this;
			//here the code 
		},
		
		/** Called after DOM´s ready.*/
		onShowView : function() {
			var that = this;

			this.modalItem = new ModalItem({
				onSelectModel : function(model) {
					that.onSelectItem(model);
				},
				suggestConfig : {
					showValue : 'name',
					field : that.ui.inputItemName
				},
				initialValue : that.model.get('item'),		
			});
		
			this.modalItemRegion.show(this.modalItem);		
		},
		
		saveAndContinue : function() {
			this.save(true)
		},

		save : function(continua) {
			var that = this;
			var permission = that.getModel();

			if (this.isValid()) {
			this.ui.saveButton.button('loading');
				permission.save({}, {
					success : function(_model, _resp, _options) {
						util.showSuccessMessage('Permissão salvo com sucesso!');
						that.clearForm();

						if (continua != true) {
							util.goPage('app/permissions', true);
						}
					},

					error : function(_model, _resp, _options) {
						that.ui.saveButton.button('reset');
						util.showErrorMessage('Problema ao salvar registro',_resp);
					}
				});
			} 
		},
		
		getModel : function() {
			var that = this;
			var permission = that.model; 
			permission.set({
				id: this.ui.inputId.escape(),
		    	name : this.ui.inputName.escape(), 
		    	description : this.ui.inputDescription.escape(), 
		    	operation : this.ui.inputOperation.escape(), 
		    	tagReminder : this.ui.inputTagReminder.escape(), 
				
				item : that.modalItem.getJsonValue(),
			});
			return permission;
		},
		
		customClearForm : function(){
			this.ui.saveButton.button('reset');
		    this.modalItem.clear(); 
		},
		showModalItem : function() {
			// add more before the modal is open
			this.modalItem.showPage();
		},
		onSelectItem : function(item) {
			this.modalItem.hidePage();	
			this.ui.inputItemId.val(item.get('id'));
			this.ui.inputItemName.val(item.get('name'));		
		},
		changeName : function() {
			var that = this;
			util.validateUnique({
				element : that.ui.inputName,
				fieldName : 'name',
				fieldDisplayName : 'Nome',
				//onlyNumber : true,     
				view : that,
				collection : Permission.PageCollection,
			})
		},				
	});

	return FormPermissions;
});