/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');	
	var PagePermissionTemplate = require('text!views/permission/tpl/PagePermissionTemplate.html');

	var ModalItem = require('views/modalComponents/ModalItem');
	var Permission = require('models/Permission');

	var PagePermission = JSetup.View.extend({
		template : _.template(PagePermissionTemplate),

		/** The declared form Regions. */
		regions : {
			dataTablePermissionRegion : '.datatable-permission',
			modalItemRegion : '.modal-item-container',
		},
		
		/** The form events you'd like to listen */
		events : {
			'click 	.reset-button' : 'resetPermission',			
			'click .search-item-modal' : 'showModalItem',
			'keypress' : 'treatKeypress',
			
			'click 	.search-button' : 'searchPermission',
			'click  .show-advanced-search-button' : 'toggleAdvancedForm',
		},
		
		/** All the important fields must be here. */		
		ui : {
			loadButton : '.loading-button',
			inputName : '#inputName',
			inputDescription : '#inputDescription',
			inputOperation : '#inputOperation',
			inputItemId : '#inputItemId',
			inputItemName : '#inputItemName',
			form : '#formPermissionFilter',
			advancedSearchForm : '.advanced-search-form',
		},
		
		/** First function called, like a constructor. */		
		initialize : function() {
			var that = this;
			this.permissions = new Permission.PageCollection();
			
			this.dataTablePermission = new JSetup.DataTable({
				columns : this.getColumns(),
				collection : this.permissions,
				onFetching : this.startFetch,
				onFetched : this.stopFetch,
				view : this
			});			
			this.modalItem = new ModalItem({
				onSelectModel : function(model) {
					that.onSelectItem(model);
				},
			});
		},

		/** Called after DOM´s ready.*/		
		onShowView : function() {
			var that = this;
		
			this.dataTablePermissionRegion.show(this.dataTablePermission);
			this.modalItemRegion.show(this.modalItem);		
		
			this.dataTablePermission.recoveryLastQuery();
		},
		
		 searchPermission : function(){		                                                                   
		 	var that = this;                                                                                                   
		 	this.dataTablePermission.getFirstPage({                                                                             
		 		success : function(_coll, _resp, _opt) {                                                                       
		 			//console.info('Consulta para o grid permission');                                         
		 		},                                                                                                             
		 		error : function(_coll, _resp, _opt) {                                                                         
		 			//console.error(_resp.responseText || (_resp.getResponseHeader && _resp.getResponseHeader('exception')));  
		 		},                                                                                                             
		 		filterQueryParams : {                                                                                          
		     		name : this.ui.inputName.escape(),                                   
		     		description : this.ui.inputDescription.escape(),                                   
		     		operation : this.ui.inputOperation.escape(),                                   
		 		    item : this.modalItem.getRawValue(),                                 
		 		}                                                                                                              
		 	})                                                                                                                 
		 },																													   
		
		resetPermission : function(){
			this.ui.form.get(0).reset();
			this.permissions.reset();
			 this.modalItem.clear(); 
		},
				
		getColumns : function() {
			var that = this;
			var columns = [
			{
				name : "name",
				sortable : true,
				editable : false,
				label 	 : "Nome",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "description",
				sortable : true,
				editable : false,
				label 	 : "Descrição",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "operation",
				sortable : true,
				editable : false,
				label 	 : "Operação",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "item.name",
				editable : false,  
				sortable : true,  
				label : "Item",
				cell : JSetup.CustomStringCell
			},	
			{
				name : "acoes",
				label : "Ações(Editar, Deletar)",
				editable : false,
				sortable : false,
				cell : JSetup.ActionCell.extend({
					buttons : that.getCellButtons(),
					context : that,
				})
			} ];
			return columns;
		},
		
		getCellButtons : function() {
			var that = this;
			var buttons = [];

			buttons.push({
				id : 'edit_button',
				type : 'primary',
				icon : 'fa-pencil',
				customClass : 'auth[edit-permission,disable]',
				hint : 'Editar Permissão',
				onClick : that.editModel,
			}, {
				id : 'delete_button',
				type : 'danger',
				customClass : 'auth[delete-permission, disable]',
				icon : 'fa-trash',
				hint : 'Remover Permissão',
				onClick : that.deleteModel,
			});

			return buttons;
		},

		deleteModel : function(model) {
			var that = this;
			
			var modelTipo = new Permission.Model({id : model.id});
			
			util.confirm({
				title : "Importante",
				text : "Tem certeza que deseja remover o registro [ " + model.get('id') + " ] ?",
				onConfirm : function() {
					modelTipo.destroy({
						success : function() {
							that.permissions.remove(model);
							util.alert({title : "Concluido", text : "Registro removido com sucesso!"});
						},
					});
				}
			});
		},

		editModel : function(model) {
			util.goPage("app/editPermission/" + model.get('id'));
		},

		showModalItem : function() {
			this.modalItem.showPage();
		},
			
		onSelectItem : function(item) {
			this.modalItem.hidePage();	
			this.ui.inputItemId.val(item.get('id'));
			this.ui.inputItemName.val(item.get('name'));		
		},
		
		// additional functions
		toggleAdvancedForm : function() {
			this.ui.advancedSearchForm.slideToggle("slow");
		},

		treatKeypress : function(e) {
			if (util.enterPressed(e)) {
				e.preventDefault();
				this.searchPermission();
			}
		},
		startFetch : function() {
			util.loadButton(this.ui.loadButton)
		},

		stopFetch : function() {
			util.resetButton(this.ui.loadButton)
		}
	});

	return PagePermission;
});
