package com.robsonmrsp.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
public class JsonActor implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private LocalDate birthDate;  			
	private String name;
	
	public  JsonActor() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public LocalDate getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(LocalDate birthDate) {
		this.birthDate = birthDate;
	}				
								
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	

}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56