package com.robsonmrsp.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
public class JsonPermission implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String description;
	private String operation;
	private String tagReminder;
	private ArrayList<JsonRole> roles = new ArrayList<JsonRole>();	
	private ArrayList<JsonGroup> groups = new ArrayList<JsonGroup>();	
	private JsonItem item;		
	
	public  JsonPermission() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}
	public String getTagReminder() {
		return tagReminder;
	}

	public void setTagReminder(String tagReminder) {
		this.tagReminder = tagReminder;
	}
	
	public ArrayList<JsonRole> getRoles() {
		return roles;
	}
	
	public void setRoles(ArrayList<JsonRole> role) {
		this.roles = role;
	}

	public ArrayList<JsonGroup> getGroups() {
		return groups;
	}
	
	public void setGroups(ArrayList<JsonGroup> group) {
		this.groups = group;
	}

	public JsonItem getItem() {
		return item;
	}
	
	public void setItem(JsonItem item) {
		this.item = item;
	}

}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56