package com.robsonmrsp.netflics.core.reports;

/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
public interface CSVColumn<T> {

	String getHeader();

	Object getValue(T t);

}
