package com.robsonmrsp.netflics.core.reports;

/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:55 */
public interface CSVColumn<T> {

	String getHeader();

	Object getValue(T t);

}
