version: '3.8'
services:
  db-postgres:
    image: postgres:11-alpine
    container_name: db_postgres
    environment:
      POSTGRES_DB: db_netflics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456a
    ports:
      - "5439:5432"
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge