/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var ActorModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/actors',

		defaults : {
			id: null,
	    	birthDate : '',    	
	    	name : '',    	
			movies : null,
		
		}
	});
	
	var ActorCollection = JSetup.BaseCollection.extend({
		model : ActorModel,
		
		url : 'rs/crud/actors',
	});
	
	var ActorsCollection = JSetup.BasePageableCollection.extend({
		model : ActorModel,

		url : 'rs/crud/actors',

		mode : 'server',
	});

	var ActorPageClientCollection = ActorsCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : ActorModel,
		Collection : ActorCollection,
	  	PageCollection : ActorsCollection,
	  	PageClientCollection : ActorPageClientCollection, 
	};
});
