/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var GroupModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/groups',

		defaults : {
			id: null,
	    	name : '',    	
	    	description : '',    	
			roles : null,
			permissions : null,
		
		}
	});
	
	var GroupCollection = JSetup.BaseCollection.extend({
		model : GroupModel,
		
		url : 'rs/crud/groups',
	});
	
	var GroupsCollection = JSetup.BasePageableCollection.extend({
		model : GroupModel,

		url : 'rs/crud/groups',

		mode : 'server',
	});

	var GroupPageClientCollection = GroupsCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : GroupModel,
		Collection : GroupCollection,
	  	PageCollection : GroupsCollection,
	  	PageClientCollection : GroupPageClientCollection, 
	};
});
