/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var ItemModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/items',

		defaults : {
			id: null,
	    	name : '',    	
	    	itemType : '',    	
	    	identifier : '',    	
	    	description : '',    	
			permissions : null,
		
		}
	});
	
	var ItemCollection = JSetup.BaseCollection.extend({
		model : ItemModel,
		
		url : 'rs/crud/items',
	});
	
	var ItemsCollection = JSetup.BasePageableCollection.extend({
		model : ItemModel,

		url : 'rs/crud/items',

		mode : 'server',
	});

	var ItemPageClientCollection = ItemsCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : ItemModel,
		Collection : ItemCollection,
	  	PageCollection : ItemsCollection,
	  	PageClientCollection : ItemPageClientCollection, 
	};
});
