/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var LanguageModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/languages',

		defaults : {
			id: null,
	    	name : '',    	
			movies : null,
		
		}
	});
	
	var LanguageCollection = JSetup.BaseCollection.extend({
		model : LanguageModel,
		
		url : 'rs/crud/languages',
	});
	
	var LanguagesCollection = JSetup.BasePageableCollection.extend({
		model : LanguageModel,

		url : 'rs/crud/languages',

		mode : 'server',
	});

	var LanguagePageClientCollection = LanguagesCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : LanguageModel,
		Collection : LanguageCollection,
	  	PageCollection : LanguagesCollection,
	  	PageClientCollection : LanguagePageClientCollection, 
	};
});
