/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var MovieModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/movies',

		defaults : {
			id: null,
	    	sinopsis : '',    	
	    	releaseDate : '',    	
	    	budget : '',    	
	    	title : '',    	
			genres : null,
			cast : null,
			language : null,
		
		}
	});
	
	var MovieCollection = JSetup.BaseCollection.extend({
		model : MovieModel,
		
		url : 'rs/crud/movies',
	});
	
	var MoviesCollection = JSetup.BasePageableCollection.extend({
		model : MovieModel,

		url : 'rs/crud/movies',

		mode : 'server',
	});

	var MoviePageClientCollection = MoviesCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : MovieModel,
		Collection : MovieCollection,
	  	PageCollection : MoviesCollection,
	  	PageClientCollection : MoviePageClientCollection, 
	};
});
