/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var PermissionModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/permissions',

		defaults : {
			id: null,
	    	name : '',    	
	    	description : '',    	
	    	operation : '',    	
	    	tagReminder : '',    	
			roles : null,
			groups : null,
			item : null,
		
		}
	});
	
	var PermissionCollection = JSetup.BaseCollection.extend({
		model : PermissionModel,
		
		url : 'rs/crud/permissions',
	});
	
	var PermissionsCollection = JSetup.BasePageableCollection.extend({
		model : PermissionModel,

		url : 'rs/crud/permissions',

		mode : 'server',
	});

	var PermissionPageClientCollection = PermissionsCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : PermissionModel,
		Collection : PermissionCollection,
	  	PageCollection : PermissionsCollection,
	  	PageClientCollection : PermissionPageClientCollection, 
	};
});
