/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var RoleModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/roles',

		defaults : {
			id: null,
	    	authority : '',    	
	    	description : '',    	
			users : null,
			permissions : null,
			groups : null,
		
		}
	});
	
	var RoleCollection = JSetup.BaseCollection.extend({
		model : RoleModel,
		
		url : 'rs/crud/roles',
	});
	
	var RolesCollection = JSetup.BasePageableCollection.extend({
		model : RoleModel,

		url : 'rs/crud/roles',

		mode : 'server',
	});

	var RolePageClientCollection = RolesCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : RoleModel,
		Collection : RoleCollection,
	  	PageCollection : RolesCollection,
	  	PageClientCollection : RolePageClientCollection, 
	};
});
