/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var Backbone = require('adapters/backbone-adapter');
	var JSetup = require('views/components/JSetup');	

	var UserModel = JSetup.BaseModel.extend({

		urlRoot : 'rs/crud/users',

		defaults : {
			id: null,
	    	name : '',    	
	    	username : '',    	
	    	email : '',    	
	    	password : '',    	
	    	enable : '',    	
	    	image : '',    	
			roles : null,
		
		}
	});
	
	var UserCollection = JSetup.BaseCollection.extend({
		model : UserModel,
		
		url : 'rs/crud/users',
	});
	
	var UsersCollection = JSetup.BasePageableCollection.extend({
		model : UserModel,

		url : 'rs/crud/users',

		mode : 'server',
	});

	var UserPageClientCollection = UsersCollection.extend({
		mode : 'client',
		state : {
			pageSize : 10,
		},
	})
	
	return {
		Model : UserModel,
		Collection : UserCollection,
	  	PageCollection : UsersCollection,
	  	PageClientCollection : UserPageClientCollection, 
	};
});
