/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
package com.robsonmrsp.netflics.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.robsonmrsp.netflics.model.Actor;
	
public interface ActorRepository extends JpaRepository<Actor, Integer> ,JpaSpecificationExecutor<Actor>{

}

//generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20