/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.robsonmrsp.netflics.model.Language;
	
public interface LanguageRepository extends JpaRepository<Language, Integer> ,JpaSpecificationExecutor<Language>{

}

//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56