/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.robsonmrsp.netflics.model.Permission;
	
public interface PermissionRepository extends JpaRepository<Permission, Integer> ,JpaSpecificationExecutor<Permission>{

}

//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56