/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:55 */
package com.robsonmrsp.netflics.persistence;

import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.robsonmrsp.netflics.model.User;

public interface UserRepository extends JpaRepository<User, Integer>, JpaSpecificationExecutor<User> {
	Optional<User> findByUsername(String username);
}