/**generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56**/
package com.robsonmrsp.netflics.core.security;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.robsonmrsp.netflics.model.User;
import com.robsonmrsp.netflics.persistence.UserRepository;

@Service
@Transactional(readOnly = true, propagation = Propagation.REQUIRES_NEW)
public class UserDetailsServiceImp implements UserDetailsService {
	private final UserRepository userRepository;

	@Autowired
	SpringSecurityUserContext context;

	@Autowired
	public UserDetailsServiceImp(UserRepository userRepository) {
		if (userRepository == null) {
			throw new IllegalArgumentException("userRepository cannot be null");
		}
		this.userRepository = userRepository;
	}

	@Override
	public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
		Optional<User> appUser = userRepository.findByUsername(username);
		if (appUser.isPresent()) {
			return appUser.get();
		}
		throw new UsernameNotFoundException("Invalid username...");
	}
}