package com.robsonmrsp.netflics.core.security;

import com.robsonmrsp.netflics.model.User;
/**
*  generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20
**/

public interface UserContext {

	User getCurrentUser();

	String getCurrentUserName();
	
	void setCurrentUser(User user);
}
