package com.robsonmrsp.netflics.core.persistence.pagination;

import java.util.List;
/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
public class Pagination<T> {

	private final Long totalRecords;
	private final List<T> results;

	public Pagination(Long totalRecords, List<T> results) {
		this.totalRecords = totalRecords;
		this.results = results;
	}

	public List<T> getResults() {
		return results;
	}

	public Long getTotalRecords() {
		return totalRecords;
	}
}