/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');

	var TemplateFormRoles = require('text!views/role/tpl/FormRoleTemplate.html');
	var MultiselectModalGroups = require('views/modalComponents/MultiselectModalGroup');
	
	var Role = require('models/Role');
	var Group = require('models/Group');			
	
	var FormRoles = JSetup.View.extend({
		template : _.template(TemplateFormRoles),

		/** The declared form Regions. */
		regions : {
			multiselectModalGroupsRegion : '.multiselect-groups-container',
		},

		/** The form events you'd like to listen */
		events : {
			'click 	.save' : 'save',
			'click 	.save-continue' : 'saveAndContinue',
			'change  #inputAuthority' : 'changeAuthority',	
			'change  #inputDescription' : 'changeDescription',	
		},
		/** All the important fields must be here. */
		ui : {
			inputId : '#inputId',
			saveButton : '.button-saving',
			inputAuthority : '#inputAuthority',
			inputDescription : '#inputDescription',
			form : '#formRole',
		},
		
		/** First function called, like a constructor. */
		initialize : function(options) {
			var that = this;
			//here the code 
		},
		
		/** Called after DOM´s ready.*/
		onShowView : function() {
			var that = this;

			this.multiselectModalGroups = new MultiselectModalGroups({
				initialValues : that.model.get('groups'),
			});
		
			this.multiselectModalGroupsRegion.show(this.multiselectModalGroups);		
		},
		
		saveAndContinue : function() {
			this.save(true)
		},

		save : function(continua) {
			var that = this;
			var role = that.getModel();

			if (this.isValid()) {
			this.ui.saveButton.button('loading');
				role.save({}, {
					success : function(_model, _resp, _options) {
						util.showSuccessMessage('Papel salvo com sucesso!');
						that.clearForm();

						if (continua != true) {
							util.goPage('app/roles', true);
						}
					},

					error : function(_model, _resp, _options) {
						that.ui.saveButton.button('reset');
						util.showErrorMessage('Problema ao salvar registro',_resp);
					}
				});
			} 
		},
		
		getModel : function() {
			var that = this;
			var role = that.model; 
			role.set({
				id: this.ui.inputId.escape(),
		    	authority : this.ui.inputAuthority.escape(), 
		    	description : this.ui.inputDescription.escape(), 
				
				groups : that.multiselectModalGroups.getJsonValue(),
			});
			return role;
		},
		
		customClearForm : function(){
			this.ui.saveButton.button('reset');
		    this.multiselectModalGroups.clear(); 
		},
		changeAuthority : function() {
			var that = this;
			util.validateUnique({
				element : that.ui.inputAuthority,
				fieldName : 'authority',
				fieldDisplayName : 'Autoridade',
				//onlyNumber : true,     
				view : that,
				collection : Role.PageCollection,
			})
		},				
		changeDescription : function() {
			var that = this;
			util.validateUnique({
				element : that.ui.inputDescription,
				fieldName : 'description',
				fieldDisplayName : 'Descrição',
				//onlyNumber : true,     
				view : that,
				collection : Role.PageCollection,
			})
		},				
	});

	return FormRoles;
});