/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');	
	var PageUserTemplate = require('text!views/user/tpl/PageUserTemplate.html');

	var User = require('models/User');

	var PageUser = JSetup.View.extend({
		template : _.template(PageUserTemplate),

		/** The declared form Regions. */
		regions : {
			dataTableUserRegion : '.datatable-user',
		},
		
		/** The form events you'd like to listen */
		events : {
			'click 	.reset-button' : 'resetUser',			
			'keypress' : 'treatKeypress',
			
			'click 	.search-button' : 'searchUser',
			'click  .show-advanced-search-button' : 'toggleAdvancedForm',
		},
		
		/** All the important fields must be here. */		
		ui : {
			loadButton : '.loading-button',
			inputName : '#inputName',
			inputUsername : '#inputUsername',
			inputEmail : '#inputEmail',
			form : '#formUserFilter',
			advancedSearchForm : '.advanced-search-form',
		},
		
		/** First function called, like a constructor. */		
		initialize : function() {
			var that = this;
			this.users = new User.PageCollection();
			
			this.dataTableUser = new JSetup.DataTable({
				columns : this.getColumns(),
				collection : this.users,
				onFetching : this.startFetch,
				onFetched : this.stopFetch,
				view : this
			});			
		},

		/** Called after DOM´s ready.*/		
		onShowView : function() {
			var that = this;
		
			this.dataTableUserRegion.show(this.dataTableUser);
		
			this.dataTableUser.recoveryLastQuery();
		},
		
		 searchUser : function(){		                                                                   
		 	var that = this;                                                                                                   
		 	this.dataTableUser.getFirstPage({                                                                             
		 		success : function(_coll, _resp, _opt) {                                                                       
		 			//console.info('Consulta para o grid user');                                         
		 		},                                                                                                             
		 		error : function(_coll, _resp, _opt) {                                                                         
		 			//console.error(_resp.responseText || (_resp.getResponseHeader && _resp.getResponseHeader('exception')));  
		 		},                                                                                                             
		 		filterQueryParams : {                                                                                          
		     		name : this.ui.inputName.escape(),                                   
		     		username : this.ui.inputUsername.escape(),                                   
		     		email : this.ui.inputEmail.escape(),                                   
		 		}                                                                                                              
		 	})                                                                                                                 
		 },																													   
		
		resetUser : function(){
			this.ui.form.get(0).reset();
			this.users.reset();
		},
				
		getColumns : function() {
			var that = this;
			var columns = [
			{
				name : "name",
				sortable : true,
				editable : false,
				label 	 : "Nome",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "username",
				sortable : true,
				editable : false,
				label 	 : "Username",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "email",
				sortable : true,
				editable : false,
				label 	 : "E-mail",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "acoes",
				label : "Ações(Editar, Deletar)",
				editable : false,
				sortable : false,
				cell : JSetup.ActionCell.extend({
					buttons : that.getCellButtons(),
					context : that,
				})
			} ];
			return columns;
		},
		
		getCellButtons : function() {
			var that = this;
			var buttons = [];

			buttons.push({
				id : 'edit_button',
				type : 'primary',
				icon : 'fa-pencil',
				customClass : 'auth[edit-user,disable]',
				hint : 'Editar Usuário',
				onClick : that.editModel,
			}, {
				id : 'delete_button',
				type : 'danger',
				customClass : 'auth[delete-user, disable]',
				icon : 'fa-trash',
				hint : 'Remover Usuário',
				onClick : that.deleteModel,
			});

			return buttons;
		},

		deleteModel : function(model) {
			var that = this;
			
			var modelTipo = new User.Model({id : model.id});
			
			util.confirm({
				title : "Importante",
				text : "Tem certeza que deseja remover o registro [ " + model.get('id') + " ] ?",
				onConfirm : function() {
					modelTipo.destroy({
						success : function() {
							that.users.remove(model);
							util.alert({title : "Concluido", text : "Registro removido com sucesso!"});
						},
					});
				}
			});
		},

		editModel : function(model) {
			util.goPage("app/editUser/" + model.get('id'));
		},

		
		// additional functions
		toggleAdvancedForm : function() {
			this.ui.advancedSearchForm.slideToggle("slow");
		},

		treatKeypress : function(e) {
			if (util.enterPressed(e)) {
				e.preventDefault();
				this.searchUser();
			}
		},
		startFetch : function() {
			util.loadButton(this.ui.loadButton)
		},

		stopFetch : function() {
			util.resetButton(this.ui.loadButton)
		}
	});

	return PageUser;
});
