/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
package com.robsonmrsp.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.robsonmrsp.netflics.core.model.Tenant ;

import com.robsonmrsp.netflics.model.Actor;
import com.robsonmrsp.netflics.persistence.ActorRepository;
import com.robsonmrsp.netflics.persistence.ActorSpecificationHelper;
import com.robsonmrsp.netflics.model.filter.FilterActor;

import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.rs.exception.ValidationException;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;
import com.robsonmrsp.netflics.core.utils.DateUtil;
import com.robsonmrsp.netflics.core.utils.Util;

@Service
@Transactional
public class ActorServiceImp implements ActorService {

	public static final Logger LOGGER = LoggerFactory.getLogger(ActorServiceImp.class);
	
	@Autowired
	ActorRepository actorRepository;
	
	public Optional<Actor> get(Integer id, Tenant tenant) {
		return actorRepository.findOne(ActorSpecificationHelper.fromId(id, tenant));
	}

	public Pager<Actor> get(SearchParameters<FilterActor> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<Actor> page = actorRepository.findAll(ActorSpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<Actor>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<Actor> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			actorRepository.delete(optional.get());
		}
		return true;
	}

	public Actor save(Actor entity) {
		return actorRepository.save(entity);
	}

	public Actor update(Actor entity) {
		return actorRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20