/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
package com.robsonmrsp.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import com.robsonmrsp.netflics.core.model.Tenant;
import com.robsonmrsp.netflics.model.Actor;
import com.robsonmrsp.netflics.model.filter.FilterActor;

import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;

public interface ActorService {

	
	public Optional<Actor> get(Integer id, Tenant tenant) ;

	public Pager<Actor> get(SearchParameters<FilterActor> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Actor save(Actor entity) ;

	public Actor update(Actor entity) ;

}
//generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20