/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
package com.robsonmrsp.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.robsonmrsp.netflics.core.model.Tenant ;

import com.robsonmrsp.netflics.model.Group;
import com.robsonmrsp.netflics.persistence.GroupRepository;
import com.robsonmrsp.netflics.persistence.GroupSpecificationHelper;
import com.robsonmrsp.netflics.model.filter.FilterGroup;

import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.rs.exception.ValidationException;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;
import com.robsonmrsp.netflics.core.utils.DateUtil;
import com.robsonmrsp.netflics.core.utils.Util;

@Service
@Transactional
public class GroupServiceImp implements GroupService {

	public static final Logger LOGGER = LoggerFactory.getLogger(GroupServiceImp.class);
	
	@Autowired
	GroupRepository groupRepository;
	
	public Optional<Group> get(Integer id) {
		return groupRepository.findById(id);
	}

	public Pager<Group> get(SearchParameters<FilterGroup> searchParams) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<Group> page = groupRepository.findAll(GroupSpecificationHelper.filter(searchParams), pageRequest);

		return new Pager<Group>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}
	
	public Boolean delete(Integer id) {
		Optional<Group> optional = this.get(id);
		if (optional.isPresent()) {
			groupRepository.delete(optional.get());
		}
		return true;
	}

	public Group save(Group entity) {
		return groupRepository.save(entity);
	}

	public Group update(Group entity) {
		return groupRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20