/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import com.robsonmrsp.netflics.core.model.Tenant;
import com.robsonmrsp.netflics.model.Language;
import com.robsonmrsp.netflics.model.filter.FilterLanguage;

import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;

public interface LanguageService {

	
	public Optional<Language> get(Integer id, Tenant tenant) ;

	public Pager<Language> get(SearchParameters<FilterLanguage> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Language save(Language entity) ;

	public Language update(Language entity) ;

}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56