/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import com.robsonmrsp.netflics.core.model.Tenant;
import com.robsonmrsp.netflics.model.Movie;
import com.robsonmrsp.netflics.model.filter.FilterMovie;

import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;

public interface MovieService {

	
	public Optional<Movie> get(Integer id, Tenant tenant) ;

	public Pager<Movie> get(SearchParameters<FilterMovie> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Movie save(Movie entity) ;

	public Movie update(Movie entity) ;

}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56