/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import com.robsonmrsp.netflics.core.model.Tenant;
import com.robsonmrsp.netflics.model.Permission;
import com.robsonmrsp.netflics.model.filter.FilterPermission;

import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;

public interface PermissionService {

	
	public Optional<Permission> get(Integer id) ;

	public Pager<Permission> get(SearchParameters<FilterPermission> searchParams) ;
	
	public Boolean delete(Integer id);

	public Permission save(Permission entity) ;

	public Permission update(Permission entity) ;

}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56