/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.service;

import java.util.Optional;

import com.robsonmrsp.netflics.core.model.Tenant ;
import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;
import com.robsonmrsp.netflics.model.User;
import com.robsonmrsp.netflics.model.filter.FilterUser;
import com.robsonmrsp.netflics.persistence.UserRepository;
import com.robsonmrsp.netflics.persistence.UserSpecificationHelper;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
public class UserServiceImp implements UserService {

	public static final Logger LOGGER = LoggerFactory.getLogger(UserServiceImp.class);
	
	@Autowired
	UserRepository userRepository;
	
	public Optional<User> get(Integer id, Tenant tenant) {
		return userRepository.findOne(UserSpecificationHelper.fromId(id, tenant));
	}

	public Pager<User> get(SearchParameters<FilterUser> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<User> page = userRepository.findAll(UserSpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<User>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<User> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			userRepository.delete(optional.get());
		}
		return true;
	}

	public User save(User entity) {
		return userRepository.save(entity);
	}

	public User update(User entity) {
		return userRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56