/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
package com.robsonmrsp.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import com.robsonmrsp.netflics.core.model.Tenant;
import com.robsonmrsp.netflics.model.User;
import com.robsonmrsp.netflics.model.filter.FilterUser;

import com.robsonmrsp.netflics.core.persistence.pagination.Pager;
import com.robsonmrsp.netflics.core.persistence.pagination.SearchParameters;

public interface UserService {

	
	public Optional<User> get(Integer id, Tenant tenant) ;

	public Pager<User> get(SearchParameters<FilterUser> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public User save(User entity) ;

	public User update(User entity) ;

}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56