/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');

	var TemplateFormGroups = require('text!views/group/tpl/FormGroupTemplate.html');
	var MultiselectModalPermissions = require('views/modalComponents/MultiselectModalPermission');
	
	var Group = require('models/Group');
	var Permission = require('models/Permission');			
	
	var FormGroups = JSetup.View.extend({
		template : _.template(TemplateFormGroups),

		/** The declared form Regions. */
		regions : {
			multiselectModalPermissionsRegion : '.multiselect-permissions-container',
		},

		/** The form events you'd like to listen */
		events : {
			'click 	.save' : 'save',
			'click 	.save-continue' : 'saveAndContinue',
			'change  #inputName' : 'changeName',	
		},
		/** All the important fields must be here. */
		ui : {
			inputId : '#inputId',
			saveButton : '.button-saving',
			inputName : '#inputName',
			inputDescription : '#inputDescription',
			form : '#formGroup',
		},
		
		/** First function called, like a constructor. */
		initialize : function(options) {
			var that = this;
			//here the code 
		},
		
		/** Called after DOM´s ready.*/
		onShowView : function() {
			var that = this;

			this.multiselectModalPermissions = new MultiselectModalPermissions({
				initialValues : that.model.get('permissions'),
			});
		
			this.multiselectModalPermissionsRegion.show(this.multiselectModalPermissions);		
		},
		
		saveAndContinue : function() {
			this.save(true)
		},

		save : function(continua) {
			var that = this;
			var group = that.getModel();

			if (this.isValid()) {
			this.ui.saveButton.button('loading');
				group.save({}, {
					success : function(_model, _resp, _options) {
						util.showSuccessMessage('Grupo de Permissões salvo com sucesso!');
						that.clearForm();

						if (continua != true) {
							util.goPage('app/groups', true);
						}
					},

					error : function(_model, _resp, _options) {
						that.ui.saveButton.button('reset');
						util.showErrorMessage('Problema ao salvar registro',_resp);
					}
				});
			} 
		},
		
		getModel : function() {
			var that = this;
			var group = that.model; 
			group.set({
				id: this.ui.inputId.escape(),
		    	name : this.ui.inputName.escape(), 
		    	description : this.ui.inputDescription.escape(), 
				
				permissions : that.multiselectModalPermissions.getJsonValue(),
			});
			return group;
		},
		
		customClearForm : function(){
			this.ui.saveButton.button('reset');
		    this.multiselectModalPermissions.clear(); 
		},
		changeName : function() {
			var that = this;
			util.validateUnique({
				element : that.ui.inputName,
				fieldName : 'name',
				fieldDisplayName : 'Nome',
				//onlyNumber : true,     
				view : that,
				collection : Group.PageCollection,
			})
		},				
	});

	return FormGroups;
});