/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
define(function(require) {
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');	
	var PageActorTemplate = require('text!views/actor/tpl/PageActorTemplate.html');

	var Actor = require('models/Actor');

	var PageActor = JSetup.View.extend({
		template : _.template(PageActorTemplate),

		/** The declared form Regions. */
		regions : {
			dataTableActorRegion : '.datatable-actor',
		},
		
		/** The form events you'd like to listen */
		events : {
			'click 	.reset-button' : 'resetActor',			
			'keypress' : 'treatKeypress',
			
			'click 	.search-button' : 'searchActor',
			'click  .show-advanced-search-button' : 'toggleAdvancedForm',
		},
		
		/** All the important fields must be here. */		
		ui : {
			loadButton : '.loading-button',
			inputBirthDate : '#inputBirthDate',
			inputName : '#inputName',
			form : '#formActorFilter',
			advancedSearchForm : '.advanced-search-form',
		},
		
		/** First function called, like a constructor. */		
		initialize : function() {
			var that = this;
			this.actors = new Actor.PageCollection();
			
			this.dataTableActor = new JSetup.DataTable({
				columns : this.getColumns(),
				collection : this.actors,
				onFetching : this.startFetch,
				onFetched : this.stopFetch,
				view : this
			});			
		},

		/** Called after DOM´s ready.*/		
		onShowView : function() {
			var that = this;
			this.ui.inputBirthDate.date();
		
			this.dataTableActorRegion.show(this.dataTableActor);
		
			this.dataTableActor.recoveryLastQuery();
		},
		
		 searchActor : function(){		                                                                   
		 	var that = this;                                                                                                   
		 	this.dataTableActor.getFirstPage({                                                                             
		 		success : function(_coll, _resp, _opt) {                                                                       
		 			//console.info('Consulta para o grid actor');                                         
		 		},                                                                                                             
		 		error : function(_coll, _resp, _opt) {                                                                         
		 			//console.error(_resp.responseText || (_resp.getResponseHeader && _resp.getResponseHeader('exception')));  
		 		},                                                                                                             
		 		filterQueryParams : {                                                                                          
		     		birthDate : this.ui.inputBirthDate.escape(),                                   
		     		name : this.ui.inputName.escape(),                                   
		 		}                                                                                                              
		 	})                                                                                                                 
		 },																													   
		
		resetActor : function(){
			this.ui.form.get(0).reset();
			this.actors.reset();
		},
				
		getColumns : function() {
			var that = this;
			var columns = [
			{
				name : "birthDate",
				sortable : true,
				editable : false,
				label 	 : "Birth date",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "name",
				sortable : true,
				editable : false,
				label 	 : "Name",
				cell : JSetup.CustomStringCell
			}, 
			{
				name : "acoes",
				label : "Ações(Editar, Deletar)",
				editable : false,
				sortable : false,
				cell : JSetup.ActionCell.extend({
					buttons : that.getCellButtons(),
					context : that,
				})
			} ];
			return columns;
		},
		
		getCellButtons : function() {
			var that = this;
			var buttons = [];

			buttons.push({
				id : 'edit_button',
				type : 'primary',
				icon : 'fa-pencil',
				customClass : 'auth[edit-actor,disable]',
				hint : 'Editar Actor',
				onClick : that.editModel,
			}, {
				id : 'delete_button',
				type : 'danger',
				customClass : 'auth[delete-actor, disable]',
				icon : 'fa-trash',
				hint : 'Remover Actor',
				onClick : that.deleteModel,
			});

			return buttons;
		},

		deleteModel : function(model) {
			var that = this;
			
			var modelTipo = new Actor.Model({id : model.id});
			
			util.confirm({
				title : "Importante",
				text : "Tem certeza que deseja remover o registro [ " + model.get('id') + " ] ?",
				onConfirm : function() {
					modelTipo.destroy({
						success : function() {
							that.actors.remove(model);
							util.alert({title : "Concluido", text : "Registro removido com sucesso!"});
						},
					});
				}
			});
		},

		editModel : function(model) {
			util.goPage("app/editActor/" + model.get('id'));
		},

		
		// additional functions
		toggleAdvancedForm : function() {
			this.ui.advancedSearchForm.slideToggle("slow");
		},

		treatKeypress : function(e) {
			if (util.enterPressed(e)) {
				e.preventDefault();
				this.searchActor();
			}
		},
		startFetch : function() {
			util.loadButton(this.ui.loadButton)
		},

		stopFetch : function() {
			util.resetButton(this.ui.loadButton)
		}
	});

	return PageActor;
});
