/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
define(function(require) {
	var _ = require('adapters/underscore-adapter');
	var $ = require('adapters/jquery-adapter');
	var util = require('utilities/utils');
	var JSetup = require('views/components/JSetup');

	var TemplateFormLanguages = require('text!views/language/tpl/FormLanguageTemplate.html');
	
	var Language = require('models/Language');
	
	var FormLanguages = JSetup.View.extend({
		template : _.template(TemplateFormLanguages),

		/** The declared form Regions. */
		regions : {
		},

		/** The form events you'd like to listen */
		events : {
			'click 	.save' : 'save',
			'click 	.save-continue' : 'saveAndContinue',
		},
		/** All the important fields must be here. */
		ui : {
			inputId : '#inputId',
			saveButton : '.button-saving',
			inputName : '#inputName',
			form : '#formLanguage',
		},
		
		/** First function called, like a constructor. */
		initialize : function(options) {
			var that = this;
			//here the code 
		},
		
		/** Called after DOM´s ready.*/
		onShowView : function() {
			var that = this;

		
		},
		
		saveAndContinue : function() {
			this.save(true)
		},

		save : function(continua) {
			var that = this;
			var language = that.getModel();

			if (this.isValid()) {
			this.ui.saveButton.button('loading');
				language.save({}, {
					success : function(_model, _resp, _options) {
						util.showSuccessMessage('Language salvo com sucesso!');
						that.clearForm();

						if (continua != true) {
							util.goPage('app/languages', true);
						}
					},

					error : function(_model, _resp, _options) {
						that.ui.saveButton.button('reset');
						util.showErrorMessage('Problema ao salvar registro',_resp);
					}
				});
			} 
		},
		
		getModel : function() {
			var that = this;
			var language = that.model; 
			language.set({
				id: this.ui.inputId.escape(),
		    	name : this.ui.inputName.escape(), 
				
			});
			return language;
		},
		
		customClearForm : function(){
			this.ui.saveButton.button('reset');
		},
	});

	return FormLanguages;
});