package com.robsonmrsp.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
public class FilterMovie implements Serializable {
	private static final long serialVersionUID = 1L;
	private String sinopsis;  			
	private LocalDate releaseDate;  			
	private Double budget;  			
	private String title;  			

	private Integer language;		
	
	public  FilterMovie() {
		
	}

	public String getSinopsis() {
		return sinopsis;
	}

	public void setSinopsis(String sinopsis) {
		this.sinopsis = sinopsis;
	}
	public LocalDate getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(LocalDate releaseDate) {
		this.releaseDate = releaseDate;
	}
	public Double getBudget() {
		return budget;
	}

	public void setBudget(Double budget) {
		this.budget = budget;
	}
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
		
	public Integer getLanguage() {
		return language;
	}
	
	public void setLanguage(Integer language) {
		this.language = language;
	}
}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56