package com.robsonmrsp.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56 */
public class FilterLanguage implements Serializable {
	private static final long serialVersionUID = 1L;
	private String name;  			

	
	public  FilterLanguage() {
		
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
		
}
//generated by JSetup v0.95 :  at 4 de jan de 2022 23:12:56