package com.robsonmrsp.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20 */
public class FilterActor implements Serializable {
	private static final long serialVersionUID = 1L;
	private LocalDate birthDate;  			
	private String name;  			

	
	public  FilterActor() {
		
	}

	public LocalDate getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(LocalDate birthDate) {
		this.birthDate = birthDate;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
		
}
//generated by JSetup v0.95 :  at 3 de jan de 2022 23:41:20